// source: services/company/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var oojob_protobuf_system_pb = require('@oojob/oojob-protobuf/system_pb.js');
goog.object.extend(proto, oojob_protobuf_system_pb);
var oojob_protobuf_place_pb = require('@oojob/oojob-protobuf/place_pb.js');
goog.object.extend(proto, oojob_protobuf_place_pb);
var oojob_protobuf_metadata_pb = require('@oojob/oojob-protobuf/metadata_pb.js');
goog.object.extend(proto, oojob_protobuf_metadata_pb);
var oojob_protobuf_cursor_pb = require('@oojob/oojob-protobuf/cursor_pb.js');
goog.object.extend(proto, oojob_protobuf_cursor_pb);
var oojob_protobuf_health_pb = require('@oojob/oojob-protobuf/health_pb.js');
goog.object.extend(proto, oojob_protobuf_health_pb);
goog.exportSymbol('proto.company.Company', null, global);
goog.exportSymbol('proto.company.CompanyAllResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.company.Company = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.company.Company.repeatedFields_, null);
};
goog.inherits(proto.company.Company, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.company.Company.displayName = 'proto.company.Company';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.company.CompanyAllResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.company.CompanyAllResponse.repeatedFields_, null);
};
goog.inherits(proto.company.CompanyAllResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.company.CompanyAllResponse.displayName = 'proto.company.CompanyAllResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.company.Company.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.company.Company.prototype.toObject = function(opt_includeInstance) {
  return proto.company.Company.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.company.Company} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.company.Company.toObject = function(includeInstance, msg) {
  var f, obj = {
    identity: (f = msg.getIdentity()) && oojob_protobuf_system_pb.Identifier.toObject(includeInstance, f),
    admin: jspb.Message.getFieldWithDefault(msg, 2, ""),
    url: jspb.Message.getFieldWithDefault(msg, 3, ""),
    logo: jspb.Message.getFieldWithDefault(msg, 4, ""),
    employees: (f = msg.getEmployees()) && oojob_protobuf_system_pb.Range.toObject(includeInstance, f),
    place: (f = msg.getPlace()) && oojob_protobuf_place_pb.Place.toObject(includeInstance, f),
    foundedYear: jspb.Message.getFieldWithDefault(msg, 7, ""),
    hiringStatus: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    skillsList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    metadata: (f = msg.getMetadata()) && oojob_protobuf_metadata_pb.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.company.Company}
 */
proto.company.Company.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.company.Company;
  return proto.company.Company.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.company.Company} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.company.Company}
 */
proto.company.Company.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new oojob_protobuf_system_pb.Identifier;
      reader.readMessage(value,oojob_protobuf_system_pb.Identifier.deserializeBinaryFromReader);
      msg.setIdentity(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdmin(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLogo(value);
      break;
    case 5:
      var value = new oojob_protobuf_system_pb.Range;
      reader.readMessage(value,oojob_protobuf_system_pb.Range.deserializeBinaryFromReader);
      msg.setEmployees(value);
      break;
    case 6:
      var value = new oojob_protobuf_place_pb.Place;
      reader.readMessage(value,oojob_protobuf_place_pb.Place.deserializeBinaryFromReader);
      msg.setPlace(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setFoundedYear(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHiringStatus(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addSkills(value);
      break;
    case 10:
      var value = new oojob_protobuf_metadata_pb.Metadata;
      reader.readMessage(value,oojob_protobuf_metadata_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.company.Company.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.company.Company.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.company.Company} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.company.Company.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentity();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      oojob_protobuf_system_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getAdmin();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLogo();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEmployees();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      oojob_protobuf_system_pb.Range.serializeBinaryToWriter
    );
  }
  f = message.getPlace();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      oojob_protobuf_place_pb.Place.serializeBinaryToWriter
    );
  }
  f = message.getFoundedYear();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getHiringStatus();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getSkillsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      oojob_protobuf_metadata_pb.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional oojob.protobuf.Identifier identity = 1;
 * @return {?proto.oojob.protobuf.Identifier}
 */
proto.company.Company.prototype.getIdentity = function() {
  return /** @type{?proto.oojob.protobuf.Identifier} */ (
    jspb.Message.getWrapperField(this, oojob_protobuf_system_pb.Identifier, 1));
};


/**
 * @param {?proto.oojob.protobuf.Identifier|undefined} value
 * @return {!proto.company.Company} returns this
*/
proto.company.Company.prototype.setIdentity = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.clearIdentity = function() {
  return this.setIdentity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.company.Company.prototype.hasIdentity = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string admin = 2;
 * @return {string}
 */
proto.company.Company.prototype.getAdmin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.setAdmin = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string url = 3;
 * @return {string}
 */
proto.company.Company.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string logo = 4;
 * @return {string}
 */
proto.company.Company.prototype.getLogo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.setLogo = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional oojob.protobuf.Range employees = 5;
 * @return {?proto.oojob.protobuf.Range}
 */
proto.company.Company.prototype.getEmployees = function() {
  return /** @type{?proto.oojob.protobuf.Range} */ (
    jspb.Message.getWrapperField(this, oojob_protobuf_system_pb.Range, 5));
};


/**
 * @param {?proto.oojob.protobuf.Range|undefined} value
 * @return {!proto.company.Company} returns this
*/
proto.company.Company.prototype.setEmployees = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.clearEmployees = function() {
  return this.setEmployees(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.company.Company.prototype.hasEmployees = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional oojob.protobuf.Place place = 6;
 * @return {?proto.oojob.protobuf.Place}
 */
proto.company.Company.prototype.getPlace = function() {
  return /** @type{?proto.oojob.protobuf.Place} */ (
    jspb.Message.getWrapperField(this, oojob_protobuf_place_pb.Place, 6));
};


/**
 * @param {?proto.oojob.protobuf.Place|undefined} value
 * @return {!proto.company.Company} returns this
*/
proto.company.Company.prototype.setPlace = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.clearPlace = function() {
  return this.setPlace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.company.Company.prototype.hasPlace = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string founded_year = 7;
 * @return {string}
 */
proto.company.Company.prototype.getFoundedYear = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.setFoundedYear = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bool hiring_status = 8;
 * @return {boolean}
 */
proto.company.Company.prototype.getHiringStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.setHiringStatus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * repeated string skills = 9;
 * @return {!Array<string>}
 */
proto.company.Company.prototype.getSkillsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.setSkillsList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.addSkills = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.clearSkillsList = function() {
  return this.setSkillsList([]);
};


/**
 * optional oojob.protobuf.Metadata metadata = 10;
 * @return {?proto.oojob.protobuf.Metadata}
 */
proto.company.Company.prototype.getMetadata = function() {
  return /** @type{?proto.oojob.protobuf.Metadata} */ (
    jspb.Message.getWrapperField(this, oojob_protobuf_metadata_pb.Metadata, 10));
};


/**
 * @param {?proto.oojob.protobuf.Metadata|undefined} value
 * @return {!proto.company.Company} returns this
*/
proto.company.Company.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.company.Company} returns this
 */
proto.company.Company.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.company.Company.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 10) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.company.CompanyAllResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.company.CompanyAllResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.company.CompanyAllResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.company.CompanyAllResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.company.CompanyAllResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    companiesList: jspb.Message.toObjectList(msg.getCompaniesList(),
    proto.company.Company.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.company.CompanyAllResponse}
 */
proto.company.CompanyAllResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.company.CompanyAllResponse;
  return proto.company.CompanyAllResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.company.CompanyAllResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.company.CompanyAllResponse}
 */
proto.company.CompanyAllResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.company.Company;
      reader.readMessage(value,proto.company.Company.deserializeBinaryFromReader);
      msg.addCompanies(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.company.CompanyAllResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.company.CompanyAllResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.company.CompanyAllResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.company.CompanyAllResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCompaniesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.company.Company.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Company companies = 1;
 * @return {!Array<!proto.company.Company>}
 */
proto.company.CompanyAllResponse.prototype.getCompaniesList = function() {
  return /** @type{!Array<!proto.company.Company>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.company.Company, 1));
};


/**
 * @param {!Array<!proto.company.Company>} value
 * @return {!proto.company.CompanyAllResponse} returns this
*/
proto.company.CompanyAllResponse.prototype.setCompaniesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.company.Company=} opt_value
 * @param {number=} opt_index
 * @return {!proto.company.Company}
 */
proto.company.CompanyAllResponse.prototype.addCompanies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.company.Company, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.company.CompanyAllResponse} returns this
 */
proto.company.CompanyAllResponse.prototype.clearCompaniesList = function() {
  return this.setCompaniesList([]);
};


goog.object.extend(exports, proto.company);
